### ISSUE TITLE
Use a different event to signal end of execution

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-task#102]
`ContextClosedEvent` is kind of final. It's very unwieldy for local development because you don't get to look at the task repository and verify that the task completed, until the context is dead (and then there's no way to introspect it). Maybe `ApplicationReadyEvent` would be better?

**Comment by mminella** [comment]
I'd have to look at how we're handling errors to see if this is even an option (@philwebb) but given that we log the event (so that you can confirm what happened in development), what is the use case you'd like to see covered?

**Comment by dsyer** [comment]
I'd like to have an app that stays up after the task completes so I can look in the local H2 and confirm that it works, for instance. You can listen to more than one event, if you want to react differently to errors (I imagine we already do that).
