### ISSUE TITLE
Add support to receive task lifecycle events from another module

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task#11]
As a user, I'd want to be able to receive task lifecycle events from another module, so I can orchestrate set of modules in a composite workflow. 

**Acceptance:**
I should be able to do something like: `fooTask | barSink` where the `fooTask` and `barSink` modules are connected by a bus to send and received events

**Comment by mminella** [comment]
Depends on https://github.com/spring-cloud/spring-cloud-stream/issues/462
