### ISSUE TITLE
Size of TASK_PARAM column needs to increase

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-task#112]
I got this:

    Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "TASK_PARAM VARCHAR(250)":

**Comment by mminella** [comment]
What are you passing in?  That's for command line args only...

**Comment by trisberg** [comment]
Trying to run my sparkapp-yarn task with some extra config options for Cloudera CDH:

    $ java -jar sparkapp-yarn-task-1.0.0.BUILD-SNAPSHOT-exec.jar --app-name=hashtags --app-class=Hashtags --app-jar=hdfs:///app/spark/spark-hashtags_2.10-0.1.0.jar --spark-assembly-jar=hdfs:///app/spark/spark-assembly_2.10-1.5.0-cdh5.5.0.jar --app-args=/tmp/tweets,/tmp/hashtags --spring.hadoop.fsUri=hdfs://192.168.59.104:8020 --spring.hadoop.resourceManagerHost=192.168.59.104 --spring.yarn.config.yarn.application.classpath='$HADOOP_CLIENT_CONF_DIR,$HADOOP_CONF_DIR,$HADOOP_COMMON_HOME/*,$HADOOP_COMMON_HOME/lib/*,$HADOOP_HDFS_HOME/*,$HADOOP_HDFS_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_YARN_HOME/lib/*,$HADOOP_MAPRED_HOME/*,$HADOOP_MAPRED_HOME/lib/*'

**Comment by mminella** [comment]
Ah.  I guess we could bump it up to 2500...However I wouldn't want to go any larger (Text, CLOB, etc) for the out of the box schema.  Thoughts?
