### ISSUE TITLE
Enable Task to accept externally generated task id

### ISSUE THREAD

**Issue by mminella** [spring-cloud/spring-cloud-task#115]
In order to allow for the time difference between when a task is requested and the infrastructure actually launches it, we'll need to be able to map the infrastructure's execution id with the task execution id.  This story is to allow that mapping to occur by having the launcher do the creation of the task execution record within the task repository.

**Comment by jvalkeal** [comment]
Once https://github.com/spring-cloud/spring-cloud-dataflow/pull/492 is merged we could have a chat about this implementation in more detailed level.

**Comment by markfisher** [comment]
spring-cloud/spring-cloud-dataflow#492 is now merged

**Comment by jvalkeal** [comment]
@mminella so only integration from tasks towards this deployment id repository is [TaskDeploymentController.java#L153](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDeploymentController.java#L153)

Similarly we now have an option to do more clever cancel(undeploy in stream):
[StreamDeploymentController.java#L370](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java#L370)

And possibly querying status from deployer point of view if task is not yet running(shell status for stream):
[StreamDefinitionController.java#L200](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java#L200)

I think this thing around execution id becomes more clear if/when we try to implement those cancel()/status() features from tasks side towards `TaskLauncher`.
