### ISSUE TITLE
`spring-cloud-task-dependencies` contains non-spring cloud task dependency management

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-task#177]
The public BOM must only contain dependency management for the current project and not force any version for "external" dependencies. As it stands, `spring-batch-core` is probably the most annoying but spring cloud stream is also affected (as its own bom provides the version to use). 

There is a pattern to deal with this in Spring Cloud and you are probably using it already so it's a matter of moving those dependencies in the other pom.

**Comment by mminella** [comment]
@snicoll What other Spring Cloud projects can you provide as an example of this?  And what do you mean by "the other pom"?

**Comment by snicoll** [comment]
The spring cloud team put that infra in place and spent some time to get it right so I'd ask them.

**Comment by mbogoevici** [comment]
The non SCSt dependencies in the SCSt-dependencies BOM have to go. We've had them there for a while and keeping them there was an oversights.

**Comment by snicoll** [comment]
The `spring-cloud-task` bom is still wrong. Can we please fix it? ping @dsyer

**Comment by dsyer** [comment]
Bump. It seems like 1.0.2 was released and this wasn't addressed.
