### ISSUE TITLE
Test task partitions on Mesos

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task#194]
As a developer, I'd like to test task partitions using SCDF's Mesos implementation and document findings.

**Comment by cppwfs** [comment]
Was able to successfully launch partitions from a task on Mesos.  However,w hile testing Task Partitioning on SCDF-Mesos, several Chronos issues popped up.

* Chronos attaches command-line-arguments to the mesos id. Thus you can't include : or / so users can't use command line args to configure jdbc properties for example. Else it will throw a ZK exception
* Once a task fails, Chronos would queue up other tasks but would not execute them.
Unable to reproduce: but on 2 occurrences tasks were left in staged but did not execute.

So the following story will be required to make task execution from the Spring Cloud Deployer Mesos production quality: https://github.com/spring-cloud/spring-cloud-task/issues/194
