### ISSUE TITLE
Test task partitions on Kubernetes

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task#195]
As a developer, I'd like to test task partitions using SCDF's Kubernetes implementation and document findings.

**Comment by cppwfs** [comment]
Produced a document here: https://docs.google.com/document/d/14KzY8dA_VgrBNhQaxbs2CZeNEcAfoDJbM8w7Xrq6KOA/edit#  
Identifying the issues that need to be resolved.
