### ISSUE TITLE
Test task partitions on YARN

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task#196]
As a developer, I'd like to test task partitions using SCDF's YARN implementation and document findings.

**Comment by cppwfs** [comment]
For this task, the goal was to utilize the Partition Sample from the SCT project, change the deployer dependency from local to Yarn, build and test the new code using SCDF-Yarn.  After a slack chat with Janne, these steps will not work.   He will make available a sample app that was used for his testing.   With this in mind, this story may lead to another conversation.  At least a blog on how to create partitioned jobs for yarn .
