### ISSUE TITLE
User wants ability to store common exit code when running multiple CommandLineRunners.

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#22]
User wants ability to store exit code using the same logic as Spring boot in cases where more than CommandLineRunnners are within the spring boot app.  Currently implementation uses last exit code in returned list.  
Using the getExitCode as a template or submitting a PR to spring boot to make SpringApplication.getExitCode public.  Here is a link to the code: https://github.com/spring-projects/spring-boot/blob/9c412232d5fe0353f0fd117ba438ed080683eee1/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L1167

**Comment by cppwfs** [comment]
Talked it over with Phil he suggested adding a ExitCodeGenerators class to Spring Boot, instead of opening up the private getExitCode from Spring Application.  
Opened issue https://github.com/spring-projects/spring-boot/issues/4757.  He said that he'd get it in by the 1.3.1 release.

**Comment by mminella** [comment]
Closing.  This will be handled by Boot.
