### ISSUE TITLE
Character ':' is invalid for file path on windows in 1.0.3.RELEASE

### ISSUE THREAD

**Issue by soiff** [spring-cloud/spring-cloud-task#242]
Hi, guys:

> `DeployerPartitionHandler#launchWorker(StepExecution)`

	AppDefinition definition =
		new AppDefinition(String.format("%s:%s:%s",
			taskExecution.getTaskName(),
			workerStepExecution.getJobExecution().getJobInstance().getJobName(),
			workerStepExecution.getStepName(),
			this.environmentVariablesProvider.getEnvironmentVariables(copyContext));

> `LocalTaskLauncher#launch(AppDeploymentRequest)`

            String e = request.getDefinition().getName() + "-" + System.currentTimeMillis();
            Path dir = Paths.get(this.logPathRoot.toFile().getAbsolutePath(), new String[]{e});
            if(!Files.exists(dir, new LinkOption[0])) {
                Files.createDirectory(dir, new FileAttribute[0]);
                dir.toFile().deleteOnExit();
            }

> `e` here contains character `:`, which is invalid on windows. Is this a bug?

**Comment by cppwfs** [comment]
Makes sense.  We can change the `:` to a _.     I'll submit a PR tomorrow.
