### ISSUE TITLE
Get datasource from `TaskConfigurer` when building batch listener

### ISSUE THREAD

**Issue by mminella** [spring-cloud/spring-cloud-task#252]
When a user defines multiple `DataSource` beans in their context, they need to create a `TaskConfigurer` to identify which one to use.  However, the autoconfiguration for the `TaskBatchExecutionListener` doesn't use that reference (although it should).  Because of this, the user needs to override the configuration of the `TaskBeanExecutionListener` in this case.  We can make this better by just recycling the reference from the `TaskConfigurer`.

**Comment by cppwfs** [comment]
While trying apply the fix above I noticed that we have another issue here.  BatchAutoConfiguration also autowires DataSources and has an expectation that only one DataSource is present.  i.e. https://github.com/spring-projects/spring-batch/blob/master/spring-batch-core/src/main/java/org/springframework/batch/core/configuration/annotation/AbstractBatchConfiguration.java#L108
