### ISSUE TITLE
Set MySQLMaxValueIncrementer "useNewConnection" to true

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-task#269]
Once Spring Framework 4.3.6 is available we should update and set MySQLMaxValueIncrementer "useNewConnection" to true. This is related to #262 and https://github.com/spring-projects/spring-framework/pull/1286

**Comment by cppwfs** [comment]
WOOOT WOOT !  Absolutely!

**Comment by trisberg** [comment]
This depends on Spring Batch 4.0 getting released or we need to bump 3.x to build against latest Spring Framework (4.3.6 or later)

**Comment by trisberg** [comment]
This now depends on merge of https://github.com/spring-projects/spring-batch/pull/455 as well as a Spring Batch 3.0.8 release (https://jira.spring.io/browse/BATCH/fixforversion/15562/)
