### ISSUE TITLE
Controll number of simultanous Tasks lunched using LocalTaskLauncher 

### ISSUE THREAD

**Issue by shahbour** [spring-cloud/spring-cloud-task#275]
I am lunching tasks using spring-cloud-deployer-local but i would like to have a feature that can control how many simultaneous tasks are run together , kind of queue or taskExecutor . 

I found that [LocalTaskLancher](https://github.com/spring-cloud/spring-cloud-deployer-local/blob/7a5449b12ed07ec2b54c2a517b5e1610d883ba33/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalTaskLauncher.java)  is responsible for the lunching but nothing about queue or checking how many app is active  

[stackoverflow](http://stackoverflow.com/questions/41912884/control-spring-cloud-task-luncher)

**Comment by cppwfs** [comment]
The scenario that you are presenting is Task Orchestration and thus would be handled by the Spring Cloud Data Flow [project](https://github.com/spring-cloud/spring-cloud-dataflow).   You are welcome to open a ticket there on this topic.
