### ISSUE TITLE
Error upgrading MySQL database

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-task#287]
I'm getting an error running the 1.2 migration script on a MySQL database:

```
alter table task_execution add PARENT_EXECUTION_ID BIGINT;
```

results in: Code: 1146 SQL State: 42S02 --- Table 'test.task_execution' doesn't exist

The table name should be uppercase since that is how it is defined in `schema-mysql.sql`

**Comment by cppwfs** [comment]
That is interesting.  I just ran it locally and it did fine from the mysql prompt:
`source /Users/glennrenfro/project/spring-cloud-task/spring-cloud-task-core/src/main/resources/org/springframework/cloud/task/migration/1.2.x/migration-mysql.sql`

**Comment by trisberg** [comment]
Is your file system case sensitive? https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html

**Comment by cppwfs** [comment]
Nope, I'm on the exception list i.e. OSX. ;-)   Will have a PR out shortly.
