### ISSUE TITLE
Add Ordered Interface to EventEmittingJobExecutionListener and other events

### ISSUE THREAD

**Issue by shahbour** [spring-cloud/spring-cloud-task#291]
I want to force my AfterJob to be executed before `EventEmittingJobExecutionListener` because i do change some properties in the context and i want these to be emitted . 

Currently `EventEmittingJobExecutionListener` is not ordered so it is being executed before the ordered .

If you agree on this i can do a PR

**Comment by cppwfs** [comment]
I don't see a problem with it.  Submit a PR and I'll take a peek.

**Comment by shahbour** [comment]
Here we go https://github.com/spring-cloud/spring-cloud-task/pull/292

I used order zero , so we can choose before or after the event
