### ISSUE TITLE
Please don't depend on Starter POMs

### ISSUE THREAD

**Issue by voidengineer** [spring-cloud/spring-cloud-task#294]
I think libraries like `spring-cloud-starter-core` and `spring-cloud-task-stream` should not depend on Spring Boot Starter POMs.

For various reasons some of my projects can not make the switch to logback as a logging backend, so I am forced to exclude `spring-boot-starter-logging` whenever I want to use `spring-cloud-task-core`.

Please only depend on those libraries and APIs you really use. If you want to provide a quick start for users of spring-cloud-task, then create additional `spring-cloud-task-*-starter`s.

**Comment by mminella** [comment]
Spring Cloud Task is a Spring Boot based project.  Spring Boot is a requirement for Spring Cloud Task to work.  What alternatives would you propose?

**Comment by voidengineer** [comment]
I have no problem if Spring Cloud Task depends on `spring-boot`, `spring-boot-autoconfigure` or even `spring-boot-actuator`, but a library like `spring-cloud-task-core` should not depend on the Starter POMs.

IMHO libraries should pull in the smallest set of dependencies that are necessary to work.
It is the same pattern with Spring Boot itself: `spring-boot` does not depend on `logback-classic`, only `spring-boot-starter` (via `spring-boot-starter-logging`)  pulls in that dependency.
