### ISSUE TITLE
Filter out executions with null in TASK_NAME

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-task#295]
Looks like launching older tasks that aren't aware that they should update the task executions rather than inserting a new row results in orphaned task execution rows with null in all fields except for ID and EXTERNAL_EXECUTION_ID. We should filter these out when listing all task executions.

See: https://github.com/spring-cloud/spring-cloud-dataflow/issues/1201

**Comment by mminella** [comment]
Filter them out from what?  I wouldn't expect a change like this to occur at the Spring Cloud Task level.

**Comment by trisberg** [comment]
From the list of executions returned by JdbcTaskExecutionDao#findAll

there is garbage rows in the db so I'd think it's the responsibility of the task db layer to filter this out

**Comment by mminella** [comment]
Filtering them out feels like we're masking a bigger problem.  I wouldn't want to just filter them out without some form of notification to the user that they should be fixed or removed.

**Comment by trisberg** [comment]
Yeah, it would be better not having these extra rows to begin with, but that would require some redesign of the new `EXTERNAL_EXECUTION_ID` feature

**Comment by mminella** [comment]
I'm open to that if there are alternatives to explore (it's new in 1.2...).  But filtering these records out without notifications doesn't make sense to me at the SCT level.  This is really a Data Flow issue (and how they interact).

**Comment by mminella** [comment]
An alternative to this would be to create a custom DAO within SCDF and do the filtering with it.  Since this isn't a Spring Cloud Task issue (it's an issue with SCDF and it's interaction with SCT), if we are going to filter this stuff out, the code should live in SCDF to do so.

**Comment by trisberg** [comment]
It seems to me that SCT is the owner of this database and repository and it defines the acceptable usage patterns. 

The current behavior is to allow a blank (nothing but `TASK_EXECUTION_ID` and ` EXTERNAL_EXECUTION_ID`) to be created for later updates by the task. This leads to other services (like SCDF) using this repo to initially show a blank execution without a `TASK_NAME` until the task is executing and filling in the rest of the info. Also, older versions of task apps never update this row, instead creating a new row without the `EXTERNAL_EXECUTION_ID`. 

If SCDF is using SCT wrong, then we should fix that, but it seems to me tat this behavior is part of the design of SCT and shouldn't have to be handled by a service that is using SCT. Solving this problem in SCDF seems to me to force a strong coupling between SCDF and SCT internals.

**Comment by mminella** [comment]
The issue isn't that SCDF is using SCT incorrectly, it's that SCDF is using a feature that doesn't exist on older versions of SCT.  I'd expect SCDF to take the responsibility for it's attempt at integrating with multiple versions and the functionality impacts for that decision.  SCT, works as designed within each of it's versions (SCT 1.2.x works fine with SCDF 1.2.x...SCT 1.1.x does not).

**Comment by trisberg** [comment]
Think we've beaten this dead horse enough ;) Let's leave as is and I added a PR to add taskName to the blank TaskExecution - https://github.com/spring-cloud/spring-cloud-task/pull/299
