### ISSUE TITLE
task-launcher-cloudfoundry-sink-rabbit-1.0.0.RELEASE missing from repo

### ISSUE THREAD

**Issue by kinsha123** [spring-cloud/spring-cloud-task#297]
Hi ,

I am trying to create a stream with task launcher but below app is missing from repo.

task-launcher-cloudfoundry-sink-rabbit-1.0.0.RELEASE

I tried to use the task-launcher-cloudfoundry-sink-rabbit-1.2.0.M1 instead but getting class not found error in pcf .

instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.cloudfoundry.reactor.ConnectionContext]: Factory method 'connectionContext' threw exception; nested exception is java.lang.NoClassDefFoundError: io/netty/handler/ssl/util/SimpleTrustManagerFactory

cf client version 6.15.0
pcf version 1.9
scdf version 1.0.0.RELEASE

Thanks

**Comment by mminella** [comment]
This is really an issue for this project: https://github.com/spring-cloud-stream-app-starters/tasklauncher-cloudfoundry  Please log the issue there.  Thanks!
