### ISSUE TITLE
Report issues for spring batch

### ISSUE THREAD

**Issue by searhiy** [spring-cloud/spring-cloud-task#315]
How can I report issues for spring batch project? Looks like [here](https://spring.io/blog/2017/04/05/spring-boot-s-new-gradle-plugin) it's disabled.

P.S. Sorry for inconvenient question

Thanks

**Comment by cppwfs** [comment]
Hello @searhiy,
You can report issues for Spring Batch here (first you must create a login): 
https://jira.spring.io/browse/BATCH/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel
