### ISSUE TITLE
How to keep PlatformTransactionManager separated?

### ISSUE THREAD

**Issue by rotilho** [spring-cloud/spring-cloud-task#316]
I have an application where I don't want to persist the Spring Cloud Task execution so I created my taskConfigurer with DefaultTaskConfigurer

```
  @Bean
    public TaskConfigurer taskConfigurer() {
        return new DefaultTaskConfigurer(null);
    }
```

The problem is that `SimpleTaskConfiguration ` always take `platformTransactionManager `from `taskConfigurer.getTransactionManager()` and create a bean with it.

So my application is trying to use `ResourcelessTransactionManager` whenever a Transaction is needed instead of the transactionManager that would be created by `JpaBaseConfiguration`.

Should TaskConfigurer override the default configuration? If yes, are there any way to keep PlatformTransactionmanager separated from the rest of the application?

**Comment by mminella** [comment]
Two items:

1. What is the use case you're using Spring Cloud Task and _not_ interested in persisting the `TaskExecution`?
2. If you want to use a different `PlatformTransactionManager`, you'd need to create your own `TaskConfigurer` that defines what one to use.

**Comment by rotilho** [comment]
1. Spring Cloud Task is something new that I have been playing. Be able to deploy it with minimal noise it's a plus however there are other kind of user cases where one application can have a different database where it keep the Spring Cloud Task executions and another one for the application
2. I'm afraid this is not possible. `SimpleTaskConfiguration` will always use `taskConfigurer` and create a bean with `transactionManager `provided by it.
3. Sorry. I thought that this were a unexpected behavior and maybe we could start discussion about it. If you agree that we should allows the application to have different `transactionManager` I can work in a PR with this change.

**Comment by mminella** [comment]
SimpleTaskConfiguration only creates a DefaultTaskConfigurer if there is
not one in the context already.

**Comment by rotilho** [comment]
Yes. Then `SimpleTaskConfiguration` create a bean with `transactionManager` provided by `TaskConfigurer`.

This doesn't looks right for me. Why is TaskConfigurer transactionManager shared with the whole application?

**Comment by mminella** [comment]
If that transaction manager isn't used it shouldn't matter.  It can be overriden if it's an issue.

**Comment by nightswimmings** [comment]
Why was this issue closed? I think it's a big issue if your main datasource to autoconfigure is different than the one used for persisting info on tasks and jobs. 

I defined a sole custom datasource in the context for JpaBaseConfiguration to build over it, including the JpaTransactionManager, but this won't be created ever, since SimpleTaskConfiguration/SimpleBatchConfiguration expose a TransactionManager.

**Comment by nightswimmings** [comment]
(Provided I configure both with a not-exposed secondary datasource)

**Comment by nightswimmings** [comment]
Indeed, as long as you are using batch+task, besides, you are forced to define @Primary TransactionManager, I presume, since they will duplicate among them
