### ISSUE TITLE
Starter version 1.2.0.RELEASE is not on maven central

### ISSUE THREAD

**Issue by kewne** [spring-cloud/spring-cloud-task#319]
Every other task artifact seems to be there, except the starter:
https://search.maven.org/#search%7Cga%7C1%7Cspring-cloud-task

Is there some other repo where we can download the artifact?

**Comment by mminella** [comment]
The artifact name was changed to match the others.  It is http://search.maven.org/#artifactdetails%7Corg.springframework.cloud%7Cspring-cloud-starter-task%7C1.2.0.RELEASE%7Cjar

**Comment by kewne** [comment]
Then the docs at: http://cloud.spring.io/spring-cloud-task/ are incorrect.
Should I open a new issue for that?

**Comment by mminella** [comment]
It should be now fixed.  Let me know if that doesn't work.  Thanks for bringing it up!

**Comment by kewne** [comment]
I can confirm it works now, thanks!
