### ISSUE TITLE
Switch "master" to 1.2.1.BS

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task#323]
As a developer, I'd like to switch `master` from 1.3.0.BS to 1.2.1.BS.

**Acceptance:**
- `master` points to 1.2.1.BS
- spring-cloud-build upgraded to [1.3.3](https://github.com/spring-cloud/spring-cloud-build/releases/tag/v1.3.3.RELEASE) (builds on Spring Boot 1.5.4)

**Comment by trisberg** [comment]
might as well also update to spring-cloud-deployer 1.2.1.BUILD-SNAPSHOT

**Comment by sabbyanandan** [comment]
And, [`spring-cloud-deployer-local`](https://github.com/spring-cloud/spring-cloud-task/blob/master/pom.xml#L142) as well.
