### ISSUE TITLE
Problem with batch-job example and spring cloud dataflow 

### ISSUE THREAD

**Issue by fbalicchia** [spring-cloud/spring-cloud-task#329]
Hi, 
batch-job example seems doesn't works when I try deployed it  in SpringCloudDataFlow local.
To make test I've used spring-cloud-task 1.2.1.RELEASE and cloud-dataflow-server-local-1.2.3.RELEASE.

To make test I've follow these steps:

* Build spring-cloud-task-samples/batch-job
* Register application in spring dataflow with url 
    `maven://io.spring.cloud:batch-job:jar:1.2.1.RELEASE` and Type Task
* from task tab define task without parameter
* run it

When I say 'seems doesn't works' I mean that in stdout.log I was waiting "Job1 was run" instead I don't find nothing and stderr was empty
Am I doing something wrong ?

Thanks for help

--Filippo

**Comment by mminella** [comment]
This is really a question for StackOverflow.  Can you please post it there?  Provide a link here and we'll be sure to respond.

**Comment by fbalicchia** [comment]
Ok, [stackoverflow](https://stackoverflow.com/questions/45493420/batch-job-example-in-spring-cloud-dataflow)
