### ISSUE TITLE
How to extend Cloud task to Nosql and legacy database

### ISSUE THREAD

**Issue by vivsrivastav** [spring-cloud/spring-cloud-task#333]
I like the clean abstraction and simplicity of using spring cloud task. I want to prototype and integrate in my project. Unfortunately i do not have the option of using relational database (company  wide decision). Is it possible to extend cloud task packages to work with

1. Nosql mainly Cassandra 
2. A legacy database

I assume i will have to write custom code. If it is possible to extend can you help provide some starting point docs, interfaces?

**Comment by mminella** [comment]
What do you mean by "a legacy database"?

**Comment by vivsrivastav** [comment]
@mminella - Foundation DB.

For the sake of this conversation i am interested to explore Cassandra support for spring cloud task

**Comment by mminella** [comment]
@vivsrivastav Casandra does not support longs for keys.  This would be a pretty big shift with minimal benefits.  Spring Batch has the same restrictions.
