### ISSUE TITLE
SimpleTaskConfiguration.verifyEnvironment has a problem

### ISSUE THREAD

**Issue by loafer** [spring-cloud/spring-cloud-task#334]
An exception is thrown when the batch that separates a business database from the batch metadata database runs in the spring cloud dataflow。The error message is "To use the default TaskConfigurer the context must contain no more than one DataSource, found 2."
```java
    @Bean
    @Primary
    @ConfigurationProperties("spring.datasource")
    public DataSource dataSource(){
        return DataSourceBuilder.create().build();
    }

    @Bean
    @ConfigurationProperties("biz.datasource")
    public DataSource bizDataSource(){
        return DataSourceBuilder.create().build();
    }

    @Bean
    public ItemWriter<Student> writer(@Qualifier("bizDataSource") DataSource dataSource) {
        .....
        return itemWriter;
    }
```

**Comment by mminella** [comment]
This is covered in the documentation here: https://docs.spring.io/spring-cloud-task/docs/1.2.2.RELEASE/reference/htmlsingle/#features-data-source  I'm closing this for now unless there is something else needed.
