### ISSUE TITLE
Upgrade to latest Spring Cloud 2.x milestone

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task#342]

**Comment by cppwfs** [comment]
Question on this.  Isn't this handled by the Spring-Cloud-Build?   Is there a reason we should jump ahead?

**Comment by mminella** [comment]
If it is, then great.  I'm honestly not sure.

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/spring-cloud/spring-cloud-task/issues/337.
