### ISSUE TITLE
Limit concurrent number of tasks running to prevent failovers

### ISSUE THREAD

**Issue by rajprasadtarget** [spring-cloud/spring-cloud-task#355]
We are creating multiple tasks in SCDF (Ex : Task 1, Task 2, Task 3) and each of these tasks do different functions. So we have three jars each for the above tasks. The users can launch these tasks from UI , so eventually, we might end with numerous concurrent tasks running at the same time which might up with resource and memory issues. So we want to limit the total number of concurrent tasks running at same time. I have seen lot of discussion around this , it will be great if a configurable  field is added in the dataflow using which we can set this. Please let me know 

Also is there anyway to queue the task request so that tasks are run when the total number of concurrent tasks running becomes less than the max number we set.

  |

**Comment by mminella** [comment]
This isn't a Spring Cloud Task issue, it's an orchestration issue which belongs to Spring Cloud Data flow.
