### ISSUE TITLE
Add Unit Tests for multiple ApplicationRunners

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#361]
Currently unit tests only cover a single Application execution.

**Comment by tyler2cr** [comment]
Hey Glenn, we're looking at working on this.

At first we assumed that we want to add tests for all subclasses of `org.springframework.boot.ApplicationRunner`, but it appears that that `org.springframework.cloud.task.batch.handler.TaskJobLauncherApplicationRunner` is the only subclass, and it has the following tests:
- `org.springframework.cloud.task.batch.handler.TaskJobLauncherApplicationRunnerCoreTests`
- `org.springframework.cloud.task.batch.handler.TaskJobLauncherApplicationRunnerTests`

Presumably this assumption needs to be refined a bit :) Which application runners do you have in mind?

**Comment by cppwfs** [comment]
Hello @tyler2cr,
Thank you for looking into the issue!   This issue should have been closed when Spring Cloud Task followed Spring Boots change over to the JobLauncherApplicationRunner.
