### ISSUE TITLE
Re-evaluate the default of the `spring.cloud.task.closecontext_enabled` flag

### ISSUE THREAD

**Issue by mminella** [spring-cloud/spring-cloud-task#364]
This flag was originally defaulted to `true` to allow users to use Spring Boot's Acuator within a Spring Cloud Task (programmatically shutting down the context) when Acuator required Tomcat.  This is no longer the case so we can change this default to `false`, allowing projects generated at start.spring.io to build successfully without modification.

**Comment by cppwfs** [comment]
Also update the documentation for testing.
