### ISSUE TITLE
Task  batch app fails when embedded hsqldb datasource and external datasource configured

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-task#405]
see https://stackoverflow.com/questions/49137988/spring-cloud-task-junit-test-case-which-uses-hsql-db-is-failing

Sample code https://github.com/dturanski/hello-world-batch-example/tree/multi_db_embedded_hsql_issue

**Comment by cppwfs** [comment]
Pulled down the project.   Removed my .m2 repo and did a fresh build.  All tests pass.  Also ran unit tests in IDE and they passed.   
I may have missed something though.  
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Intellij IDEA 2017.2.6

**Comment by cppwfs** [comment]
Found it.  The example did not have @EnableTask .   But getting a different error.

**Comment by cppwfs** [comment]
The previous error was my bad.  Still can't reproduce. I created a PR against your repo.  From that I was able to build, test and run the example.

**Comment by dturanski** [comment]
The bug is on the db_embedded_sql_issue branch

**Comment by cppwfs** [comment]
The cause of the issue is that he dataSource is null  when the TaskRepositoryInitializer.afterPropertiesSet is called.  This is when the tables are created.

**Comment by cppwfs** [comment]
[Scenario]
- User creates an app with multiple datasources
- User then creates their own TaskConfigurer Bean

[Explanation]
So at this point the SimpleTaskConfiguration validation will accept this scenario as valid.  
Here is the fun part.
1. When the taskRepositoryInitializer Bean is created it checks to see if there is exactly 1 dataSource, if so it sets the DataSource for the TaskRepositoryInitializer, which means the creation scripts will be run.  
2. If there isn't exactly 1 DataSource, then no DataSource is set for the TaskRepositoryInitializer and thus the creation scripts will not be run.  

[Solution for discussion]
When TaskRepositoryInitializer is being configured it should use the TaskConfigurer that was selected by the getDefaultConfigurer() method to determine which dataSource to use.

**Comment by dturanski** [comment]
LGTM; Thanks!
