### ISSUE TITLE
Update CF section of the batch docs to include the latest CF-deployer stack

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task#412]
As a developer, I'd like to update the [batch-docs](https://github.com/spring-cloud/spring-cloud-task/blob/a2a9d598e73fb4997bc36e1aedfebfeedd576be7/spring-cloud-task-docs/src/main/asciidoc/batch.adoc#notes-on-developing-a-batch-partitioned-application-for-the-cloud-foundry-platform) to point to the latest CF-deployer stack, so the dependencies correctly line-up with the latest Reactor stack.

**Acceptance:**
- Download task app from initializer, add the dependencies as listed in the docs, and build the project. Verify that there aren't any old Boot/Reactor dependencies in the CP
- Verify that with the latest CF-deployer and stack upgrade, the partitioned batch-job runs OK in CF

Depends on spring-cloud/spring-cloud-deployer-cloudfoundry#240

**Comment by sabbyanandan** [comment]
Update: 1.4 BS of CF-deployer include the latest Reactor stack.

**Comment by mminella** [comment]
Resolved via 486ef0dec35be2cbdb0709d535e1a8bf5712a32d.
