### ISSUE TITLE
SimpleTaskConfiguration.verifyEnvironment always fails

### ISSUE THREAD

**Issue by michael-wirth** [spring-cloud/spring-cloud-task#416]
The method` SimpleTaskConfiguration.verifyEnvironment()` will always fail when using the default setup.

The change in the `RefreshAutoConfiguration` in the spring-cloud-commons project will create 2 `datasource` definitions by default. ("datasource", "scopeTarget.datasource" (refresh scope))

see https://github.com/spring-cloud/spring-cloud-commons/blame/master/spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshAutoConfiguration.java#L94

Possible solutions to make it work with this setup are:
- remove `com.zaxxer.HikariCP` from the classpath
- define `spring.datasource.type` not using `com.zaxxer.hikari.HikariDataSource`
- disable refresh scope -  `spring.cloud.refresh.enabled=false`
- use custom `TaskConfigurer`

Tested with 
- spring-boot-version = 2.0.1.RELEASE
- spring-cloud-version=Finchley.M9

**Comment by cppwfs** [comment]
I believe this was resolved via https://github.com/spring-cloud/spring-cloud-task/issues/407.   Can you verify that the lastest master resolves this issue for you.

**Comment by cppwfs** [comment]
@michael-wirth thanks for checking!
