### ISSUE TITLE
TaskConfigurer does not considering schema name for datasource

### ISSUE THREAD

**Issue by sumanmaity112** [spring-cloud/spring-cloud-task#418]
I have 2 data source. For one data source, I want to use custom **schema name**. For this reason, I am setting my data source url like
`spring.datasource.url=jdbc:postgresql://192.168.33.10/analytics?currentSchema=bahmni_mart_scdf`.
But it's creating all the tables in **public** schema, instead of **bahmni_mart_scdf** schema.

I already override `TaskRepositoryInitializer` bean and implements `TaskConfigurer`.

Any help how to make it work properly?

**Comment by sabbyanandan** [comment]
Hi, @sumanmaity112. Thanks for your interest in Spring Cloud Task!

To use two different datasources in Boot, you could follow the approach discussed in this thread [here](https://stackoverflow.com/questions/30337582/spring-boot-configure-and-use-two-datasources?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa). However, for it to work, you'd have to turn off the default Task repository initialization completely. See details [here](https://docs.spring.io/spring-cloud-task/docs/2.0.0.RC1/reference/htmlsingle/#features-table-initialization).

Lastly, we recommend StackOverflow for questions and for problems, it'd be as GitHub issues. Going forward, if you could adapt to this model, that'd be great.
