### ISSUE TITLE
Usage of *Repository and *Dao is confusing

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-task#426]
In SCT the usage of ***Repository** versus ***Dao** seems extremely  confusing. Especially since Spring Data uses ***Repository** synonymously with ***Dao**

I would suggest a delineation around ***Service** and ***Repository**.

**Comment by ghillert** [comment]
See also https://github.com/spring-cloud/spring-cloud-task/pull/425

In that regard: Confusingly `JdbcTaskExecutionDaoTests` uses both `TaskRepository` and `JdbcTaskExecutionDao`

**Comment by mminella** [comment]
This naming strategy is carried over from Spring Batch.  We don't have any intention of changing it.
