### ISSUE TITLE
Upgrade 1.2.x line to be on Java 8

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task#429]
As a developer, I'd like to upgrade the [Java compatibility on 1.2.x](https://github.com/spring-cloud/spring-cloud-task/blob/1.2.x/pom.xml#L148) line to be Java 8. The dependent [Local-deployer](https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/pom.xml#L18) is already on that version.

**Comment by mminella** [comment]
It should run with java 8, we just don't build it with java 8 and have no intention of rebaselining on a minor version.

**Comment by sabbyanandan** [comment]
Thanks.
