### ISSUE TITLE
`@ConditionalOnProperty` target property with no metadata

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-task#442]
Several auto-configurations use a condition on a property that has no metadata. As a result, trying to use it to customize the auto-configuration lead to a warning in an IDE.

The report detected the following:

```
org.springframework.cloud.task.batch.configuration.TaskBatchAutoConfiguration [spring.cloud.task.batch.listener.enable|spring.cloud.task.batch.listener.enabled]
org.springframework.cloud.task.batch.configuration.TaskJobLauncherAutoConfiguration [spring.cloud.task.batch.failOnJobFailure]
org.springframework.cloud.task.batch.listener.BatchEventAutoConfiguration [spring.cloud.task.batch.events.enabled]
org.springframework.cloud.task.batch.listener.BatchEventAutoConfiguration.JobExecutionListenerConfiguration#chunkEventsListener [spring.cloud.task.batch.events.chunk.enabled]
org.springframework.cloud.task.batch.listener.BatchEventAutoConfiguration.JobExecutionListenerConfiguration#itemProcessEventsListener [spring.cloud.task.batch.events.item-process.enabled]
org.springframework.cloud.task.batch.listener.BatchEventAutoConfiguration.JobExecutionListenerConfiguration#itemReadEventsListener [spring.cloud.task.batch.events.item-read.enabled]
org.springframework.cloud.task.batch.listener.BatchEventAutoConfiguration.JobExecutionListenerConfiguration#itemWriteEventsListener [spring.cloud.task.batch.events.item-write.enabled]
org.springframework.cloud.task.batch.listener.BatchEventAutoConfiguration.JobExecutionListenerConfiguration#jobExecutionEventsListener [spring.cloud.task.batch.events.job-execution.enabled]
org.springframework.cloud.task.batch.listener.BatchEventAutoConfiguration.JobExecutionListenerConfiguration#skipEventsListener [spring.cloud.task.batch.events.skip.enabled]
org.springframework.cloud.task.batch.listener.BatchEventAutoConfiguration.JobExecutionListenerConfiguration#stepExecutionEventsListener [spring.cloud.task.batch.events.step-execution.enabled]
org.springframework.cloud.task.configuration.SingleTaskConfiguration [spring.cloud.task.singleInstanceEnabled]
org.springframework.cloud.task.listener.TaskEventAutoConfiguration [spring.cloud.task.events.enabled]  
```

Also, please note that properties in `@ConditionalOnPropety` have to be defined with the canonical format (so `spring.cloud.task.singleInstanceEnabled` must be `spring.cloud.task.single-instance-enabled` for instance).

**Comment by snicoll** [comment]
@jvalkeal the default value for a Boolean type is the Boolean value, not its string representation.

**Comment by cppwfs** [comment]
Opened to resolve the Boolean vs String Representation  issue. https://github.com/spring-cloud/spring-cloud-task/issues/467

**Comment by jvalkeal** [comment]
Thx, good point as I really didn't get that into my radar!

**Comment by jvalkeal** [comment]
I wonder if there is good `rules` to follow in tests to catch correct format? Does boot enforce some rules or is it just using your eyes to catch these things?

**Comment by snicoll** [comment]
I reviewed the commit manually.

It's interesting. I guess we could analyze the default value and verify that it matches the target type. Feel free to open an issue.

**Comment by jvalkeal** [comment]
Sorry I now realised you used IDE manually. Thought you had a some sort of automatic scanner to get a report of some illegal things found in a spring space.

**Comment by snicoll** [comment]
IntelliJ IDEA is very smart (auto-completion for JSON, etc) which is why I didn't bother until now. The report is in IJ as well and built in in the latest 2018.3 release.

**Comment by jvalkeal** [comment]
Right, I don't use idea, only sts which is a bit pain as you always need a real project and jars to test things which is a pain to do. Maybe I was a bit naive that metadata processor might enforce some things. But having said that, it might be interesting idea to make things a bit clever to enforce us to do things in a correct way.

**Comment by cppwfs** [comment]
PR created https://github.com/spring-cloud/spring-cloud-task/pull/468.   Thanks for catching this!
