### ISSUE TITLE
Increase the error message field size

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#445]
In this issue a user has requested that we increase the size of the error message to capture more of the stack trace. : https://github.com/spring-cloud/spring-cloud-dataflow/issues/2422

**Comment by mminella** [comment]
Without making it a CLOB/TEXT field, we can't really do that reliably across all platforms (to my knowledge).  This feels like something the user should customize themselves instead of us changing the defaults.

**Comment by cppwfs** [comment]
Agreed.

**Comment by Rostish** [comment]
How i can increase the field size?
What is the point in this field if its not informative? Could you explain me usecases for it?
