### ISSUE TITLE
Task execution exit code should note be `0` when it is null

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-task#459]
From TaskExecution's `getExitCode` method [here](https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-core/src/main/java/org/springframework/cloud/task/repository/TaskExecution.java#L125), we should not return `0` if it is null. 

When set to exit code `0`, it could implicitly depict the successful completion of the task.

**Comment by sabbyanandan** [comment]
This has been already addressed in v2.1.
