### ISSUE TITLE
Task app launching/restarting batch-jobs depending on properties (conflict with Enable task.batch.failOnJobFailure )

### ISSUE THREAD

**Issue by JohannesM24** [spring-cloud/spring-cloud-task#525]
Hi,

i want to be able to restart or launch a job depending on properties.
I achieved this by writing my own CommandLineRunner that uses a jobOperator.

A sample application would be one that processes files.
With three properties : `batch.jobname`, `batch.filename` and `batch.restart`
So I can launch a task with properties : job1, file1, false
If I then see the job failed, I can launch the same task with properties: job1, file1, true
(This is useful, if i know another service that was called in the processing was down and is up now again)
If batch.restart == true, I lookup the lastExecution of job1 and restart via the JobOperator.
And if batch.restart == false, I just launch the nextInstance.

To disable autostart of jobs I set `spring.batch.job.enabled: false` 
As I also wanted my task to fail if any of the jobs fail I set `spring.cloud.task.batch.failOnJobFailure: true` aswell

But this annotationn makes use of [tasks own CommandLineRunner](
https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-batch/src/main/java/org/springframework/cloud/task/batch/handler/TaskJobLauncherCommandLineRunner.java) that will just launch all available jobs.

[Here](https://gitlab.com/jmundorf/spring-cloud-task-timestamp-batch) is an example of the launch/restart functionality for the timestamp example.

So I think I either need another approach to separate launching and restarting or override the TaskJobLauncherCommandLineRunner.java ?

**Comment by mminella** [comment]
Can't you do this with SpEL and the existing tools?  Something like `spring.batch.job.enabled: ${!batch.restart}` and things like that..

**Comment by JohannesM24** [comment]
Setting the properties is not the problem I think. It is more like once `spring.cloud.task.batch.failOnJobFailure: true ` is set, jobs will be autostarted, even when `spring.batch.job.enabled: false` is set. Maybe there should be a way to get the monitoring of the jobs without automatically starting them.

**Comment by cppwfs** [comment]
We need to add the spring.batch.job.enabled conditionalonproperty as shown here:https://github.com/spring-projects/spring-boot/blob/2376f973f41053bd82724ba54c204baa59b268cc/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/batch/BatchAutoConfiguration.java#L86
to
https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-batch/src/main/java/org/springframework/cloud/task/batch/configuration/TaskJobLauncherAutoConfiguration.java#L51
