### ISSUE TITLE
Properties used buy TaskRepositoryInitializer should be in TaskProperties 

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#587]
Currently `spring.cloud.task.initialize.enable` and `spring.cloud.task.tablePrefix` are only referenced via the `@Value`  in the TaskRepositoryInitializer.  Thus when a user tries to access them via properties in their IDE, the IDE marks them as not found/incorrect.   Refer to issue https://github.com/spring-cloud/spring-cloud-task/issues/584

**Comment by Manokethan** [comment]
Hello @cppwfs 

I got the same problem with spring.cloud.task.name property...

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-task/commit/7490f8b82026c175902e0b3bbefd0d5d69b9104b.
