### ISSUE TITLE
Removing javadoc:aggregate from the Maven command

### ISSUE THREAD

**Issue by Buzzardo** [spring-cloud/spring-cloud-task#591]
I tinkered with it a while, but I cannot get the Javadoc to generate from the docs module and cannot get it to generate without putting `javadoc:aggregate` at the end of the Maven command line. Our other projects do not have this requirement, so I'd like to make this one match.

**Comment by marcingrzejszczak** [comment]
I don't follow. What exactly is the problem?

**Comment by cppwfs** [comment]
@Buzzardo will have the most information on this issue. 
The Java docs are not created when the documentation is built for this project.  In order to get the java docs maven has to be rerun with ` javadoc:aggregate` .

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-build/issues/133
