### ISSUE TITLE
Continuous integration and the Javadoc requirement

### ISSUE THREAD

**Issue by Buzzardo** [spring-cloud/spring-cloud-task#593]
As mentioned in https://github.com/spring-cloud/spring-cloud-task/issues/591, the Maven command line has to include `javadoc:aggregate` at the end. That's true for the CI, too. In short, we need to make sure the CI generates the Javadoc, because the build breaks if it doesn't.

**Comment by mminella** [comment]
Resolved.  I updated both the main and the latest JVM builds to use the new command.

**Comment by Buzzardo** [comment]
Thank you. :)
