### ISSUE TITLE
couldn't deploy a task on spring cloud dataflow server?

### ISSUE THREAD

**Issue by singhprashant1998** [spring-cloud/spring-cloud-task#596]
https://drive.google.com/open?id=1vkd0s9ddAEvNTZShsKQeeeuev0atqP1S
Here, i have tried to deploy a task on spring cloud dataflow. I have tried a lot.

**Comment by singhprashant1998** [comment]
Spring cloud data flow server running on localhost:9393/dashboard
designed a spring boot project called scdfdemo:
https://drive.google.com/open?id=1JGYVx8__v9vfPF4WuvLmukqiYEVQ-zGT

Desined a spring boot application as task called taskdemo
https://drive.google.com/open?id=1L9cIKrFW04oPpyIJSHNeNM1a-9UEoTNE

added taskdemo as task on server dashboard 
functionality of the task is to read from the database and write into the csv called file2.csv
taskdemo when run as standalone application is performing the desired task to write into the csv
uri for the task i gave as file://home/prashantsingh/Desktop/STS_Workspace/taskdemo/target/hello-0.0.1-SNAPSHOT.jar
https://drive.google.com/open?id=1tx2JenrRMDZYn1qMh6MY6uMOET-3vOTm

but when i add the taskdemo as task and launch the task. It displays launched task successfully on ui.
but it doesn't write into the csv once launched as task
https://drive.google.com/open?id=13QKUEtBzbP85RwOGRJSvmE87TqEhCMQK

when i saw the logs generated in the tmp folder
https://drive.google.com/open?id=11LT7W-U2K0nVVlHFl92MwxvUr28tnbWH

and when i run the command on the terminal (this command is run once task is launched): /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /home/prashantsingh/Desktop/STS_Workspace/taskdemo/target/hello-0.0.1-SNAPSHOT.jar --spring.cloud.task.executionid=2

This was the error file:
https://drive.google.com/open?id=1b-EZNBWCTmyEfTf1ZdJws7DlLh7LMkyE

Please help me with this. I have tried a lot!

**Comment by cppwfs** [comment]
Hello singhprashant1998,
Please provide code that demonstrates the issue through github. 
Also you can provide logs via the issue ie.
```
this is my log
```

**Comment by singhprashant1998** [comment]
> Hello singhprashant1998,
> Please provide code that demonstrates the issue through github.
> Also you can provide logs via the issue ie.
> 
> ```
> this is my log
> ```

**Comment by singhprashant1998** [comment]
> Hello singhprashant1998,
> Please provide code that demonstrates the issue through github.
> Also you can provide logs via the issue ie.
> 
> ```
> this is my log
> ```

**Comment by singhprashant1998** [comment]
Hi,
This is my spring cloud data flow server application called sdfdemo
https://github.com/singhprashant1998/scdfdemo

I launched a task application on the spring cloud data flow server. This task reads from a database and writes in the csv.  The task is :
https://github.com/singhprashant1998/taskdemo

The problem is if i use h2 database the task is launched successfully but when i used mysql database, the task was not launched successfully. I tried adding every necessary properties in application.properties file. But it fails using mysql db. Please help me!
[stdout.log](https://github.com/spring-cloud/spring-cloud-task/files/3093705/stdout.log)<---this is my log when i use h2 database it's successful

but 
when i used mysql
[stdout.log](https://github.com/spring-cloud/spring-cloud-task/files/3093712/stdout.log)<---this was my log when i used mysql (unsuccess). I tried a lot.

**Comment by singhprashant1998** [comment]
> Hello singhprashant1998,
> Please provide code that demonstrates the issue through github.
> Also you can provide logs via the issue ie.
> 
> ```
> this is my log
> ```

Hi,
This is my spring cloud data flow server application called sdfdemo
https://github.com/singhprashant1998/scdfdemo

I launched a task application on the spring cloud data flow server. This task reads from a database and writes in the csv. The task is :
https://github.com/singhprashant1998/taskdemo

The problem is if i use h2 database the task is launched successfully but when i used mysql database, the task was not launched successfully. I tried adding every necessary properties in application.properties file. But it fails using mysql db. Please help me!
stdout.log<---this is my log when i use h2 database it's successful

but
when i used mysql
stdout.log<---this was my log when i used mysql (unsuccess). I tried a lot.

**Comment by cppwfs** [comment]
Hello @singhprashant1998  A couple of things I noticed.   
1) Your Spring Cloud Task must have access to the same database that Spring Cloud Data Flow is using.  So in your case you must include a MySql or MariaDB dependency in the pom.xml file of  your Spring Cloud Task Project.  
2) https://github.com/singhprashant1998/taskdemo/blob/master/pom.xml#L72-L81   You are including 2 different versions of Spring Cloud Task in your dependencies.   You should only need:		```
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-task</artifactId>
	<version>1.2.3.RELEASE</version>
</dependency>
```

**Comment by singhprashant1998** [comment]
Hi @cppwfs 
I have done the required changes and pushed the changes in the taskdemo repository. I added mysql depencdency in pom.xml and removed spring-cloud-task-core dependency. But while building the jar i got an error in the console
[error.log](https://github.com/spring-cloud/spring-cloud-task/files/3094765/error.log)
so, i again added spring-cloud-task-core dependency and again built the jar. it was success this time while building the jar 
[success.log](https://github.com/spring-cloud/spring-cloud-task/files/3094777/success.log)
I launched the task from scdfdemo(server). launch again got unsuccessful as task log was as follows
[stdout.log](https://github.com/spring-cloud/spring-cloud-task/files/3094781/stdout.log)
it's like as a standalone jar the jar runs and the csv got written but as a launch from scdf , it fails with mysql again..

**Comment by cppwfs** [comment]
I found a few issues with your POM and your configuration:  
I simplified your pom file as shown below:
1. Used dependency management and got rid version numbering as much as possible
1. Added H2 for testing
1. Added spring-boot-starter-jdbc required for task
1. I replaced the mysql driver with mariadb so that I could verify that it works with the default dataflow.  (You will want to reset that back to mysql)
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.4.RELEASE</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.hello</groupId>
	<artifactId>hello</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>hello</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>Greenwich.SR1</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		<!-- JPA Data (We are going to use Repositories, Entities, Hibernate, etc...) -->

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<!-- Use MySQL Connector-J -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.opencsv</groupId>
			<artifactId>opencsv</artifactId>
			<version>4.1</version>
		</dependency>
		<dependency>
			<groupId>org.mariadb.jdbc</groupId>
			<artifactId>mariadb-java-client</artifactId>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-task</artifactId>
		</dependency>

		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
		</dependency>

	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```
Cleaned up your application.properties so that test will work and DataFlow can establish the database to use:

```
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
spring.batch.initialize-schema=always
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
```

**Comment by singhprashant1998** [comment]
@cppwfs I have updated the changes in my taskdemo application. This time jar build successfully completed. But the task launch again failed from spring cloud data flow server application. This time i have attached the dump file of the database(info) in which i am using user table to retrieve data from and writing the data into file2.csv located at /home/prashantsingh/Documents/csvfile/file2.csv . It's not working with mysql. 
dump : https://github.com/singhprashant1998/taskdemo/blob/master/test.sql
This is the log file generated after i launched the task:
[stdout.log](https://github.com/spring-cloud/spring-cloud-task/files/3095860/stdout.log)

These are few screenshots of launch task failure:

![Screenshot from 2019-04-19 00-31-20](https://user-images.githubusercontent.com/36139046/56385242-39df3500-623c-11e9-8bc1-f2be3004df94.png)
![Screenshot from 2019-04-19 00-31-53](https://user-images.githubusercontent.com/36139046/56385244-3a77cb80-623c-11e9-9e80-0ddc832f0f9e.png)
![Screenshot from 2019-04-19 00-32-13](https://user-images.githubusercontent.com/36139046/56385246-3a77cb80-623c-11e9-84b2-117d4adbba1d.png)

do i have an error in the code which i have written to read the data from the info database and write in the csv file or it's the spring cloud data flow server application which could not keep track of the tasks launched using mysql database? Because the same task application works fine on being launched using h2 database!

**Comment by cppwfs** [comment]
It looks like your trying to use H2.  From your log file:
```
Caused by: java.lang.IllegalStateException: Cannot load driver class: org.h2.Driver
	at org.springframework.util.Assert.state(Assert.java:94) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:224) ~[spring-boot-autoconfigure-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.initializeDataSourceBuilder(DataSourceProperties.java:176) ~[spring-boot-autoconfigure-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration.createDataSource(DataSourceConfiguration.java:44) ~[spring-boot-autoconfigure-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari.dataSource(DataSourceConfiguration.java:88) ~[spring-boot-autoconfigure-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari$$EnhancerBySpringCGLIB$$b854bf03.CGLIB$dataSource$0(<generated>) ~[spring-boot-autoconfigure-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
```

Is your SCDF using H2 instead of mysql.  If you want to use H2 for your task app remove the `<scope>test</scope>` from the H2 dependency in your task app pom.xml.

**Comment by singhprashant1998** [comment]
By default, my scdf application was using h2 biecause in my scdfdemo application i have not explicitly provided the spring.datasource.url and other properties in the application.properties for mysql. How can i configure my sdfdemo application to use mysql? for now i have downloaded the mysql connector in the pom.xml of the scdfdemo application. can you please tell where else i have to change in scdfdemo application?
https://github.com/singhprashant1998/scdfdemo

**Comment by cppwfs** [comment]
set `spring.datasource`  properties for the SCDF application.  Via one of the methods provided by spring boot (command line args, environment etc)  For example:

```
export spring_datasource_url=jdbc:mysql://localhost:3306/practice
export spring_datasource_username=root
export spring_datasource_password=password
export spring_datasource_driverClassName=com.mysql.jdbc.Driver
```

**Comment by singhprashant1998** [comment]
Hi @cppwfs The task is successfully deployed on the spring cloud data flow. Thanks for your help and guidance!

**Comment by Abhiram533** [comment]
@singhprashant1998  how to work with scdf task i am facing same issue with task can u help me , with your steps
