### ISSUE TITLE
Add support for MariaDB for Task schemas

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#602]
Since Mariadb is diverging from mysql, we need to support their own table creation scripts.   

Question:
Do we want to version sensitive table creation scripts.   Mariadb 10.3 supports sequences.

**Comment by sabbyanandan** [comment]
It seems, today, we are treating MariaDB as MySQL DB type in the framework. Is this issue pertain to moving away from that assumption?

**Comment by cppwfs** [comment]
we can close this as stale.
