### ISSUE TITLE
Task status is never set to KO when I use a bootstrap file and an exception is thrown in a task

### ISSUE THREAD

**Issue by dcuvilliers** [spring-cloud/spring-cloud-task#605]
I'm working on the Greenwich RELEASE version of Spring Cloud.

I have created a Task connected to my config server and set spring.cloud.task.batch.fail-on-job-failure to true.

When an exception is thrown in my Task, in case I use a bootstrap file, the status of the Task is never in error. I have the right status when I remove the connection to the config server and add an application file.

After investigation, here's what I think I understood: in the `BootstrapApplicationListener` class, a new `CloseContextOnFailureApplicationListener` listener has been added. This listener supports the `ApplicationFailedEvent` event. To put the status of the Task in error, the `TaskLifecycleListener` listener is also based on the `ApplicationFailedEvent` event. Unfortunately, `CloseContextOnFailureApplicationListener` processes the `ApplicationFailedEvent` event first and returns a `ContextClosedEvent` event via the `context.close()` method. This event ends the Task but via the method `TaskLifecycleListener.stop()` without updating the fact that the task is in error.

Afterwards, it is finally the `TaskLifecycleListener` that supports the `ApplicationFailedEvent` event but as the Task is already finished, the task status is not updated.

How can I run a Task with a configuration server and have the right status (OK, KO)? Can I change the order of the listeners so that the `ApplicationFailedEvent` event is first processed by `TaskLifecycleListener`?

**Comment by cppwfs** [comment]
was able to reproduce

**Comment by dcuvilliers** [comment]
Thanks @cppwfs I will test it as soon as possible.
