### ISSUE TITLE
Use  task name for TASK_LOCK.LOCK_KEY

### ISSUE THREAD

**Issue by venkatasreekanth** [spring-cloud/spring-cloud-task#613]
When setting singleInstanceEnabled=true, a entry is made tasklock(lock_key column) using UUIDConverter, is there a reason to use UUID and not simply pass the spring.cloud.task.name,
the reason I ask this we have had times where our network has issues and the job fails to clear the lock
I have built external workarounds to detect a job that failed to clear it's lock and clear the lock. It would be much easier to clear the lock if it didn't use UUID.

To strengthen the argument, I would point to this article
https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing

**Comment by mminella** [comment]
The locking functionality is based on Spring Integration's distributed locking functionality so this issue is better asked of them.  We can reopen this if they feel it's appropriate to change it.

**Comment by venkatasreekanth** [comment]
You want me to open an issue with them or are you doing it?
