### ISSUE TITLE
Task apps launched using partitioning should have parent task id populated.

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#618]
This can be done by passing the spring.cloud.task.parent-execution-id property to the child task execution at launch time.

**Comment by cppwfs** [comment]
This issue was opened to support SCDF's ability to stop child tasks launched by a partitioned app.  In this case the partitioned app does this already.

**Comment by Yusufyes123** [comment]
In same piece of code while setting taskExecution.setExitCode(1) but still receiving exit code 0.
