### ISSUE TITLE
Composed task custom condition

### ISSUE THREAD

**Issue by vBandiTv** [spring-cloud/spring-cloud-task#635]
I saw an examples for FAILED and UNKNOWN, so I've created 2 custom conditions Worked & Generated. Assuming this approach is possible - How do i pass those strings from inside the task? Or it needs to be passed from somewhere else? If not - then why it is possible write any string that i want in the "Properties for TRANSITION" modal instead of some dropdown?

[An example](https://i.stack.imgur.com/tfNUn.png)

**Comment by mminella** [comment]
Closing this as it is a question more pertinent for StackOverflow than opening an issue here.  If you post a question there and tag it with `spring-cloud-task`, we will address it there for the entire community to share.
