### ISSUE TITLE
spring-cloud-task-dependencies:2.2.0.RELEASE causes the spring hoxton.release project not to work properly

### ISSUE THREAD

**Issue by m1ngyuan** [spring-cloud/spring-cloud-task#638]
Maven parent of Maven dependency library spring-cloud-task-dependencies:2.2.0.RELEASE references spring-cloud-dependencies-parent:2.2.0.M1, which causes the spring houston.release project not to work properly

  https://github.com/spring-cloud/spring-cloud-release/issues/178

**Comment by cppwfs** [comment]
Please use Spring-cloud-dependencies 2.2.1.RELEASE
