### ISSUE TITLE
TASK_LOCK is not cleared when using single-instance-enabled option.

### ISSUE THREAD

**Issue by cow630** [spring-cloud/spring-cloud-task#640]
I have followed the steps in the documentation to implement the single-instance-enabled option for my Spring Cloud Task Application.  

I added the following to my application.yml
single-instance-enabled:  true   

I added the following dependencies to my pom.xml
	<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-core</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-jdbc</artifactId>
		</dependency>

Behavior:
The first task execution will run, record an entry in the task_lock table, task will complete normally.   The record is not removed from task_lock even when the task has completed.

The second task execution will fail, because task_lock record still exists from the first run.

**Comment by cppwfs** [comment]
What version of Task are you using.
What database and version are you using.

**Comment by cow630** [comment]
Hello, please see below for versions.

spring-cloud-task-core 2.1.3.RELEASE
spring-cloud-starter-task 2.1.3.RELEASE
Oracle 12.1.0.2.0

**Comment by cppwfs** [comment]
This looks to be an issue for Oracle databases.  I've isolated it to Spring Integration and will talk with them and verify.  An addition issue was discussed in Data Flow here: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3631

**Comment by cow630** [comment]
Very good.  Thanks for the update.

**Comment by cppwfs** [comment]
The issue seems to be with DefaultLockRepository in SI.   Created issue https://github.com/spring-projects/spring-integration/issues/3129

**Comment by cppwfs** [comment]
We've identified the issue and will submit a PR to resolve it.  But in the meantime you can change the LOCK_KEY and CLIENT_ID from CHAR2 to VARCHAR2.
You can alter the table `TASK_LOCK` table using the following commands:
```
ALTER TABLE TASK_LOCK MODIFY LOCK_KEY VARCHAR2(36);
ALTER TABLE TASK_LOCK MODIFY CLIENT_ID VARCHAR2(36);
```
or Drop the table and recreate it with the DDL below:
```
CREATE TABLE TASK_LOCK  (
	LOCK_KEY VARCHAR2(36) NOT NULL,
	REGION VARCHAR2(100) NOT NULL,
	CLIENT_ID VARCHAR2(36),
	CREATED_DATE TIMESTAMP NOT NULL,
	constraint LOCK_PK primary key (LOCK_KEY, REGION)
);
```

**Comment by cow630** [comment]
Fantastic.  This is great.   I've tested the workaround in my development and it is working fine.

So an official fix will be provided in future release?

**Comment by cppwfs** [comment]
Yes the schemas will be updated in the 2.3 release of Task as well as the next maintenance release of 2.2.x.

**Comment by ilopezv** [comment]
Same problem here.

It seems that Spring close context without waiting to spring task to complete the task_lock deletion.

We try following options without success:
```yaml
spring:
  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 30s
    scheduling:
      shutdown:
        await-termination: true
        await-termination-period: 30s
````
And configure TaskExecutor with 

```java
@Configuration(proxyBeanMethods = false)
public class AsyncConfiguration implements TaskExecutorCustomizer {

 @Override
 public void customize(ThreadPoolTaskExecutor taskExecutor) {
	log.trace("Customization of ThreadPoolTaskExecutor");
	taskExecutor.setWaitForTasksToCompleteOnShutdown(true);
	
 }
}
```
