### ISSUE TITLE
Need to support TaskJobLauncherApplicationRunner in Boot 2.3

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#645]
- [x] Deprecate `TaskJobLauncherCommandLineRunner` in SCT 2.3.x
- [x] Support `TaskJobLauncherApplicationRunner` to work with Boot 2.3 (SCT 2.3.x)

**Hint:** Update TaskJobLauncherAutoConfiguration to choose whether to use TaskJobLauncherCommandLineRunner or TaskJobLauncherApplicationRunner based on if TaskJobLauncherCommandLineRunner or JobLauncherApplicationRunner is in the classpath.

**Comment by sabbyanandan** [comment]
Addressed in Boot via: https://github.com/spring-projects/spring-boot/issues/19861.
