### ISSUE TITLE
Unify the docs in spring cloud task

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-task#668]
All the other spring cloud projects have a `reference/html/index.html` page that points to the entry for the docs. For task it's `reference/index.html`

**Comment by sabbyanandan** [comment]
While we are fixing this, let's also make the generated PDF visible at the https://docs.spring.io/spring-cloud-task/docs/2.3.0-M1/. 

Example: https://docs.spring.io/spring-cloud-task/docs/2.3.0-M1/reference/index.pdf
