### ISSUE TITLE
Users need sequence table to use MYISAM

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#69]
As discussed here the engine for the table should be ISAM vs. InnoDB.

http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jdbc/support/incrementer/MySQLMaxValueIncrementer.html

**Comment by trisberg** [comment]
Just to clarify, it should be MYISAM for the sequence table and the other tables should be InnoDB
