### ISSUE TITLE
Wrong cell used in table in docs

### ISSUE THREAD

**Issue by vidgeus** [spring-cloud/spring-cloud-task#729]
Problem: table is displaying shifted values due to extra pipe characters in `appendix-task-repository-schema` file.

![image](https://user-images.githubusercontent.com/13273119/94808623-b0043700-03f1-11eb-8be0-234f45ddfab5.png)

**Comment by BatoolMM** [comment]
Hi @cppwfs , Can you assign it to me, please?

**Comment by Augilar** [comment]
I have corrected the docs, but my PR has got 'All checks have failed'. #731
@cppwfs please help.

**Comment by cppwfs** [comment]
I apologize for not closing this issue sooner.  It was handled by PR https://github.com/spring-cloud/spring-cloud-task/pull/731 and has been merged.
