### ISSUE TITLE
Incorrect rendering of some text in preface.adoc

### ISSUE THREAD

**Issue by vidgeus** [spring-cloud/spring-cloud-task#730]
See below image for how the rendering of references to different doc formats is not correct:
![image](https://user-images.githubusercontent.com/13273119/94809478-f3ab7080-03f2-11eb-9116-a76b9e9dc153.png)

**Comment by cppwfs** [comment]
Hmm...   I'm not seeing this.  Which URL are you using?

**Comment by vidgeus** [comment]
> Hmm... I'm not seeing this. Which URL are you using?

this one: https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-docs/src/main/asciidoc/preface.adoc
but the same is true on my local. I use this plugin to view the adoc files: https://plugins.jetbrains.com/plugin/7391-asciidoc

**Comment by cppwfs** [comment]
@vidgeus Thank you for bringing this up!
