### ISSUE TITLE
Allow the user to select the transactionManager to use for TaskRepository

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#769]
Currently Task Repositories use `@transactional("springCloudTaskTransactionManager")`.   This should be replaced with a property i.e.
`@transactional("${spring.cloud.task.transaction-manager:transactionManager}")`.  
Also remove springCloudTaskTransactionManager bean.

This is for 3.0.0 release of SCT.

**Comment by cppwfs** [comment]
This was feature was added here: https://github.com/spring-cloud/spring-cloud-task/commit/e4581420b04e872f8aac4cb3ad8bab62bbe9c941

**Comment by GeniusMagnus** [comment]
Recently, I had to make use of the _spring.cloud.task.transaction-manager_ property. On this occasion I observed that class SimpleTaskAutoConfiguration still instantiates a (useless) transaction manager which is not injected into the application context. This could be optimized.

**Comment by cppwfs** [comment]
@GeniusMagnus created [issue](https://github.com/spring-cloud/spring-cloud-task/issues/954) to investigate.

**Comment by GeniusMagnus** [comment]
@cppwfs : Thank you! I actually thought nobody would be interested in my comment as this ticket was closed nearly two years ago. 😏

**Comment by cppwfs** [comment]
@GeniusMagnus thank you for reaching out!   It is much appreciated!
