### ISSUE TITLE
Unexpected parameters in batch jobs from previous executions

### ISSUE THREAD

**Issue by hpoettker** [spring-cloud/spring-cloud-task#770]
The two task batch runners

- [`TaskJobLauncherCommandLineRunner`](https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-batch/src/main/java/org/springframework/cloud/task/batch/handler/TaskJobLauncherCommandLineRunner.java) (deprecated since 2.3)
- [`TaskJobLauncherApplicationRunner`](https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-batch/src/main/java/org/springframework/cloud/task/batch/handler/TaskJobLauncherApplicationRunner.java) (new with 2.3)

contain equivalent logic. In particular, their methods `execute` are completely identical.

In the `execute` method, there are two surprising sources that add parameters from previous job executions to the current execution:

- If the job instance exists, and the last job execution is failed or stopped, and the job is restartable, then parameters from the last job execution are explicitly recovered and added. Whether this logic is actually sound, is hard to say. In the light of the discussion https://github.com/spring-projects/spring-batch/issues/882 I'd say that it is not.
- If the job instance does not exist, then the call to `JobParametersBuilder::getNextJobParameter` may add unwanted parameters as the last execution of a job is searched only by name of the job within that method. All parameters from that last execution will then be added with the run id (if `RunIdIncrementer` is used) increased by one.

Please have a look whether the current logic works as intended. If yes, please consider providing some guidance on it in the documentation.

**Comment by hpoettker** [comment]
I had a second a look at the first case above, i.e. the existing job instance with a failed or stopped job execution. Maybe I don't fully understand the underlying logic but the code seems redundant too me: Why would I merge the identifying parameters from the previous job execution with those of the current job execution when I assume that they belong to the same job instance? Shouldn't the identifying parameters of both executions coincide without further action since the identifying parameters define the job instance?

For the second case I've written a [minimal example](https://github.com/hpoettker/spring-cloud-task-gh-770). The only interesting file is `TaskConfiguration`:

```
@Configuration
@EnableTask
@EnableBatchProcessing
public class TaskConfiguration {
	
	@Bean
	public Job job(
		JobBuilderFactory jobBuilderFactory,
		StepBuilderFactory stepBuilderFactory
	) {
		Step step = stepBuilderFactory.get("step")
			.tasklet((contribution, chunkContext) -> RepeatStatus.FINISHED)
			.build();
		
		return jobBuilderFactory.get("job")
			.incrementer(new RunIdIncrementer())
			.start(step)
			.build();
	}
	
}
```

First, I start a MySQL container and build the code:

```
$ docker run -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=task -d mysql:5.7.25
$ ./gradlew build
```

Then, I start the application four times:

```
$ java -jar build/libs/task-0.0.1-SNAPSHOT.jar foo=bar -yada=yada
$ java -jar build/libs/task-0.0.1-SNAPSHOT.jar foo=bar
$ java -jar build/libs/task-0.0.1-SNAPSHOT.jar foo=baz
$ java -jar build/libs/task-0.0.1-SNAPSHOT.jar abc=def
```

From the logs, one can see that the job executions do not only contain the passed parameters but also parameters from previous executions:

```
o.s.b.a.b.JobLauncherApplicationRunner   : Running default command line with: [foo=bar, -yada=yada]
o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] launched with the following parameters: [{run.id=1, yada=yada, foo=bar}]
...
o.s.b.a.b.JobLauncherApplicationRunner   : Running default command line with: [foo=bar]
o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] launched with the following parameters: [{run.id=2, yada=yada, foo=bar}]
...
o.s.b.a.b.JobLauncherApplicationRunner   : Running default command line with: [foo=baz]
o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] launched with the following parameters: [{run.id=3, yada=yada, foo=baz}]
...
o.s.b.a.b.JobLauncherApplicationRunner   : Running default command line with: [abd=def]
o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] launched with the following parameters: [{abd=def, run.id=4, yada=yada, foo=baz}]
```

**Comment by cppwfs** [comment]
This isn't a Spring Cloud Task issue.  You can raise this issue in the Spring Batch.   
In your example above if you remove the Task dependencies, you will get the same behavior.

**Comment by hpoettker** [comment]
@cppwfs Thanks for having a look at this.

The core of the problem is that once a job with an incrementer has been started with some parameter, this parameter can only be changed to something else. But it cannot be unset which is however desirable for non-identifying parameters.

It's the method call to `JobParameterBuilder::getNextJobParameter` from Spring Batch that adds the old parameters. One could argue that it shouldn't but changing this would break the current behavior of other classes within Spring Batch.

Please consider re-opening this ticket.

My first version of the minimal example invoked Spring Boot's `JobLauncherApplicationRunner` and not `TaskJobLauncherApplicationRunner`. I changed the example by setting `spring.cloud.task.batch.fail-on-job-failure=true` such that it uses `TaskJobLauncherApplicationRunner`. The change is visible in the logs. The described behaviour is unchanged, however.

Just for completeness: I stumbled on the issue with Spring Cloud Data Flow and the job that is built by the Composed Task Runner. When a user mistypes an argument in the free text field for launching a composed task, this is surprisingly hard to get rid of.

**Comment by cppwfs** [comment]
Hello @hpoettker,
Thank you for describing you issue and opening a PR.   In this case I would recommend, opening this issue in Spring Boot rather than batch as I previously suggested (my mistake).   In this case Spring Cloud Task is building its TaskJobLauncherApplicationRunner to add additional functionality to what is provided in Spring Boot.   This feature you are requesting is a change in the behavior from what is provided in boot.    Raise this issue in Spring Boot and see if they will agree to make the change.   

Thanks again, for raising this issue.   I will also close the PR.
