### ISSUE TITLE
Remove TaskJobLauncherCommandLineRunner

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#776]
As of Boot 2.5.x JobLauncherCommandLineRunner has been removed.   It has been deprecated since Boot 2.3.  So following this change, Spring Cloud Task needs to remove TaskJobLauncherCommandLineRunner

**Comment by philwebb** [comment]
@cppwfs I've now restored the class. We'll have another go at removing it in Spring Boot 2.6.

**Comment by cppwfs** [comment]
TaskJobLauncherCommandLineRunner has been removed as of 2.4.
