### ISSUE TITLE
DB2 Pagination uses the between which includes one more entry than is required.   

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#780]
Update https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-core/src/main/java/org/springframework/cloud/task/repository/database/support/Db2PagingQueryProvider.java#L33-L35 with:
		return generateRowNumSqlQueryWithNesting(getSelectClause(),
				"TMP_ROW_NUM >= " + offset + " AND TMP_ROW_NUM < " + (offset + pageable.getPageSize()));

**Comment by cppwfs** [comment]
Similar fix is found here: https://github.com/spring-cloud/spring-cloud-dataflow/pull/4441/files

**Comment by tyler2cr** [comment]
Hey @cppwfs , 

We've submitted a pull request with a fix for this issue, and included a docker test that verifies the behavior. 

The pull request can be viewed here: https://github.com/spring-cloud/spring-cloud-task/pull/840
