### ISSUE TITLE
Mariadb needs to be treated as a independent db type.

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#833]
Currently Task treats mariadb as a version of MySql.   Task needs to treat mariadb as its own type.

**Comment by fmbenhassine** [comment]
We have the same request for Spring Batch here: https://github.com/spring-projects/spring-batch/issues/3891.

While SF was updated to treat MariaDB as an independent database, I believe Batch and Task need a dedicated incrementer as described here: https://github.com/spring-projects/spring-framework/pull/28355#issuecomment-1275698440, to be able to implement this feature correctly.

**Comment by cppwfs** [comment]
a special thanks to @ben-enfuse-io for his efforts on this PR.
