### ISSUE TITLE
Task (pod) runs indefinitely only when a TaskException is triggered

### ISSUE THREAD

**Issue by nightswimmings** [spring-cloud/spring-cloud-task#835]
I have an issue with a spring-cloud-starter-task 2.3.1 (using spring-batch underneath) running on Kubernetes. The task stays running indefinitely, when TaskException is thrown, even though its lifecycle seems properly closed, since the exitcode is 1 and the database registers all task_execution metadata correctly as it finished. This only happens when the underlying batch job throws an Exception, when no exception everything completes smooth.

After debugging, when TaskJobLauncherApplicationRunner gets an underlying spring-batch job exception, its method throwJobFailedException ends up in a wrapped org.springframework.cloud.task.listener.TaskException that produces a 

java.lang.IllegalStateException: Failed to execute ApplicationRunner\n\tat org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)

and the context is never closed so the task remains as RUNNING.

If I enter the pod and send a SIGTERM to the java process it finishes instantaneously, without the need of SIGKILL.

I am tempted to think the following is a Task bug, for the fact that :
 - The Spring-Boot ApplicationRunner ends with IllegalState (Illegal means usually that this situation should not be logically expected) and this makes me think somehow the Task exception is breaking the bootstrap process and that is what gets the context unclosed
 - When no TaskException is triggered, the pod completes well, so it seems something related to the way spring-cloud-task signals spring-boot to end app exceptionally

**Comment by cppwfs** [comment]
Hello @nightswimmings,
I was unable to reproduce the error with the information provided above.   
Please upgrade to Spring Cloud Task 2.4.1 because Spring Cloud Task 2.3.1 is no longer under OSS Support.
Could you provide a simple task-batch project that exhibits the problem that you have presented using the latest supported Task/Batch/Boot versions?  
As a workaround you can set the `spring.cloud.task.closecontextEnabled` to `true` and this will close the context at the end of the task run.

**Comment by nightswimmings** [comment]
Thanks for the answer @cppwfs!
I already tried closecontextEnabled and it does not help because my problem is that spring-boot runner exits abruptly, it does not seem to even try to shutdown gracefully the context. Ill try with the supported version you indicate, and if still happens Ill try to build a simple-task-batch, thanks a lot

**Comment by nightswimmings** [comment]
@cppwfs  I fixed it with:

`
   public static void main(String[] args) {
        try {
            int exitCode = SpringApplication.exit(SpringApplication.run(MyApp.class, args));
            System.exit(exitCode);
        } catch (TaskException e) {
            // Might be related to https://github.com/spring-projects/spring-boot/issues/27049, check after migration to Boot 2.6+
            System.exit(1);
        }
    }
`

**Comment by cppwfs** [comment]
@nightswimmings Sounds good.
