### ISSUE TITLE
Reference documentation: single HTML is broken

### ISSUE THREAD

**Issue by alexismanin** [spring-cloud/spring-cloud-task#865]
Hi,

I've tried to access the single page documentation of the project using this link:

https://docs.spring.io/spring-cloud-task/docs/current/reference/htmlsingle/

However, instead of documentation content, I see AsciiDoc `include` commands printed:

```
include::preface.adoc[leveloffset=+1]

include::getting-started.adoc[leveloffset=+1]

...
```

Regards,

**Comment by cppwfs** [comment]
@alexismanin thank you for reporting this issue.   It was resolved with the following commit: https://github.com/spring-cloud/spring-cloud-task/commit/ae2f8984bef538c2e19e7cafdf6dab67916f1c2d.
