### ISSUE TITLE
`TaskRepository` does not depend on database initializers

### ISSUE THREAD

**Issue by hpoettker** [spring-cloud/spring-cloud-task#874]
Currently, the `TaskRepository` does not have an explicit dependency on database initializers, neither on `TaskRepositoryInitializer` nor on e.g. Liquibase or Flyway. This can lead to issues with lazy bean initialization.

The following toy application based on Spring Boot 3.0.0-RC1 and Spring Cloud Task 3.0.0-RC1 shows one such issue: https://github.com/hpoettker/lazy-task

The application 
- contains a dummy `ApplicationRunner`,
- uses an H2 embedded database,
- has enabled lazy bean initialization,
- has disabled the `TaskRepositoryInitializer`,
- and uses Liquibase to create the task database schema (which is just the default schema in this simple example).

When the application is started, it fails as the database schema DDL statements are not executed.

The problem is that no bean has an explicit dependency on `SpringLiquibase`. As the beans in the application are initialized lazily by default, this means that `SpringLiquibase` is never initialized. Accordingly, the app works if a `LazyInitializationExcludeFilter` is exposed for beans of type `SpringLiquibase`.

The problem can be resolved with the PR #789.

**Comment by cppwfs** [comment]
@hpoettker Thank you once again for identifying an issue and providing a great sample that shows the behavior.

**Comment by cppwfs** [comment]
Merged via PR# https://github.com/spring-cloud/spring-cloud-task/pull/789
Thank you for the issue, the PR, and the sample!
