### ISSUE TITLE
TaskJobLauncherApplicationRunner overrides default job launcher behavior

### ISSUE THREAD

**Issue by aritzbastida** [spring-cloud/spring-cloud-task#882]
According to the Spring Cloud Task reference documentation, the property `spring.cloud.task.batch.fail-on-job-failure` can be set to `true `in order to exit with code 1 when a Spring Batch fails. 

I would just expect that implemented with an application event listener subscribed to `JobExecutionEvent`, but I was surprised to find out that switching on this toggle changes the default application runner altogether. Spring Boot's `JobLauncherApplicationRunner` is replaced with `TaskJobLauncherApplicationRunner`, and that overrides internal behavior such as checking previous job executions, incrementing job parameters and the like. Also, unlike `JobLauncherApplicationRunner`, the jobs are monitored with a polling interval, but normally, the JobLauncher implementation should use a `SyncTaskExecutor` in a standalone (task) context. 

Why is all this necessary? And if so, shouldn't this be clearly documented?

**Comment by cppwfs** [comment]
Update TaskJobLauncherApplicationRunner behavior to match JobApplicationRunner behavior.

**Comment by cppwfs** [comment]
Documentation needs to be updated.

**Comment by cppwfs** [comment]
Could you provide the Spring Cloud Task, Spring Batch, and Spring Boot versions where this issue occurred?
Also can you provide a small sample app that exhibits the behavior?  
Thank You!

**Comment by aritzbastida** [comment]
Sure thing. The versions are as follows: Spring Cloud Task 2.4.3, Spring Batch 4.3.6, Spring Boot 2.7.1.

I also attach the sources of a test application. You can turn on/off the property "spring.cloud.task.batch.fail-on-job-failure" in application.yml, as needed.

Summing up, my concerns/questions are:
* `TaskJobLauncherApplicationRunner` is a subclass of `JobLauncherApplicationRunner`, but, in addition to exiting with code 1 when the batch fails, it "overrides" the default behavior altogether (calculating job parameters, monitoring job output, etc.). I don't really understand why two different runners are necessary, and if so, what is the difference between them.
* In case the only expected behavior is exiting with code 1, auto-configuring a default ExitCodeExceptionMapper with @ConditionalOnMissingBean should be enough, in line with the [reference documentation of Spring Cloud Task](https://docs.spring.io/spring-cloud-task/docs/current/reference/html/#features-task-execution-details). 
* Indeed, I implemented such a thing in the attached test app (see code snippet below). This class propagates the batch exit status to task exit message, and returns a different exit code depending on the error type. 
_NOTE: This configuration only works with the default JobLauncherApplicationRunner (fail-on-job-failure=false). For some reason, ApplicationEventPublisher is not autowired to TaskJobLauncherApplicationRunner and thus the application event listener is not called._

```java
public final class BatchExitCodeExceptionMapper implements ApplicationListener<JobExecutionEvent>, ExitCodeExceptionMapper {
	
	private String exitMessage;
	
	@Override
	public void onApplicationEvent(JobExecutionEvent event) {	
		JobExecution execution = event.getJobExecution();
		
		exitMessage = execution.getExitStatus().getExitCode();
		
		if(execution.getStatus().equals(BatchStatus.FAILED)) {
			throw new JobFailedException(execution);
		}
	}
	
	@Override
	public int getExitCode(Throwable exception) {		
		Throwable cause = exception.getCause();

        	if (cause instanceof JobExecutionException) { // JobExecutionAlreadyRunningException, etc.        	
            		return ExitCodes.JOB_LAUNCH_FAILED.ordinal();            
        	} else if (cause instanceof JobFailedException) {         	
        		return ExitCodes.JOB_EXECUTION_FAILED.ordinal();        	
        	} else {        	
            		return ExitCodes.UNKNOWN_ERROR.ordinal();	
        	}
	}			
	
	@AfterTask
	public void onTaskEnd(TaskExecution taskExecution) {
		taskExecution.setExitMessage(exitMessage);		
	}	

	private enum ExitCodes {
		OK,
		JOB_EXECUTION_FAILED,
		JOB_LAUNCH_FAILED,		
		UNKNOWN_ERROR	
	}
}
```

[test-app.zip](https://github.com/spring-cloud/spring-cloud-task/files/10227281/test-app.zip)

**Comment by hpoettker** [comment]
Most of the logic from `TaskJobLauncherApplicationRunner.execute` seems duplicated from `JobLauncherApplicationRunner.execute`. It's structured very differently but I think it's equivalent.

The problem seems to me that `JobLauncherApplicationRunner` does not have an extension point that would allow to use the logic in its private method `getNextJobParameters` and get access to the `JobExecution`s except through the `JobExecutionEvent`s.

Maybe Spring Boot is willing to provide such an extension point. Then the duplicated code could be removed without re-building the logic around event listeners.

**Comment by cppwfs** [comment]
@hpoettker You are correct in that it was created because there was no extension point with `JobLauncherApplicationRunner`.   But as you discussed here and with your PR, I think we can approach the Boot team about adding it.

**Comment by hpoettker** [comment]
> For some reason, ApplicationEventPublisher is not autowired to TaskJobLauncherApplicationRunner and thus the application event listener is not called.

This is a separate issue. I've opened a PR for it: #889

**Comment by hpoettker** [comment]
I've updated #888, which now uses the publishing of the `JobExecutionEvent`s as extension point.

The new approach works because the default `ApplicationEventMulticaster` invokes all listeners synchronously. Therefore, the execution path is very similar to the current. It would stop working if e.g. a multi-threaded executor is used for invoking the listeners. But is this really a problem? An application that uses both the `TaskJobLauncherApplicationRunner` and a custom setup for handling `ApplicationEvent`s seems unlikely to me.

**Comment by cppwfs** [comment]
The root cause of this issue is resolved  here: https://github.com/spring-cloud/spring-cloud-task/commit/4ea9b9fa214f3fc594faf6ed8616a1d3166f1d04 as it pertains to the JobExecutionEvent.   As far as the duplicate it is being discussed on #888 .
