### ISSUE TITLE
Multiple TransactionManager Beans available

### ISSUE THREAD

**Issue by Manu10744** [spring-cloud/spring-cloud-task#899]
I am having a batch application that I want to run both from IDE / Command Line and in Spring Cloud Dataflow. 
For this I included 

```xml
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-task</artifactId>
</dependency>
```
in Version `3.0.2`.

I have to inject a TransactionManager in my step methods according to the `.chunk(int, TransactionManager)` JavaDoc
```java
@Bean
public Step myStep(PlatformTransactionManager transactionManager,
                       JobRepository jobRepository,
                       FlatFileItemReader<MyEntity> reader,
                       ItemProcessor<MyEntity, MyEntity> processor,
                       JpaItemWriter<MyEntity> entityWriter) {
```

This causes

```bash
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.exportDetailsProvider' defined in class path resource [de/faktorzehn/vwb/batch/exporter/ExportBatchJobConfiguration.class]:
 Failed to instantiate [de.faktorzehn.vwb.batch.exporter.ExportDetailsProvider]: Factory method 'exportDetailsProvider' threw exception with message: No qualifying bean of type 'org.springframework.transaction.TransactionManager' available: 
expected single matching bean but found 2: transactionManager,springCloudTaskTransactionManager
```

I found an Issue where a fix was provided, which added the property `spring.cloud.task.transaction-manager` that is supposed to prevent this `springCloudTaskTransactionManager` to be created if said property is present. I added this property to my application.yaml `spring.cloud.task.transaction-manager: transactionManager` but the error message didnt vanish.

**Comment by cppwfs** [comment]
Hello @Manu10744,
Please provide a sample application that reproduces the issue.   
Thank you

**Comment by Manu10744** [comment]
I've found the spot in my code thats causing this behavior, I'm working on a example and will post it asap

**Comment by cppwfs** [comment]
There were a couple of hiccups in your sample but you can set the transactionManager for your transaction as shown below:
```
@Component
@Transactional("transactionManager")
public class NoOpRepository {

    @PersistenceContext
    private EntityManager em;

    public void clear() {
        em.clear();
    }

}
```

**Comment by Manu10744** [comment]
Many Thanks!
