### ISSUE TITLE
misprint in spring-cloud-task 4.1.0-M2 release 

### ISSUE THREAD

**Issue by OleksandrShkurat** [spring-cloud/spring-cloud-task#925]
I've got a notification about a new release of `spring-cloud-task` and it looks like there is a misprint:
![image](https://github.com/spring-cloud/spring-cloud-task/assets/10740620/79f6a7fa-7037-4ce9-a99c-ef335c8a49c7)

**Comment by cppwfs** [comment]
Thank you!   Will update

**Comment by cppwfs** [comment]
Thank you for the alert!!!!   Updated
