### ISSUE TITLE
Update link to snapshot documentation

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#927]
Currently the opening paragraph in the reference documentation has a link to the old location of the snapshot docs [here](https://docs.spring.io/spring-cloud-task/docs/current-SNAPSHOT/reference/html/).   Update it to the new location: https://docs.spring.io/spring-cloud-task/reference/

**Comment by dashaun** [comment]
🚀 @harpreets789 Your PR got merged!  I'm happy for you AND the community!  Thank you!
