### ISSUE TITLE
Jar versions in the Single Step Batch Job  sample readme are out of date

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#931]
Currently, the version numbers for the Single Step Batch Job jar files in the [README](https://github.com/spring-cloud/spring-cloud-task/blob/main/spring-cloud-task-samples/single-step-batch-job/README.adoc) need to be updated to the current snapshot version of Spring Cloud Task.   Please update the following jar versions to `3.1.0-SNAPSHOT`, e.g.: `target/single-step-batch-job-3.1.0-SNAPSHOT.jar`.
 
For example:
* https://github.com/spring-cloud/spring-cloud-task/blob/main/spring-cloud-task-samples/single-step-batch-job/README.adoc?plain=1#L43
* https://github.com/spring-cloud/spring-cloud-task/blob/main/spring-cloud-task-samples/single-step-batch-job/README.adoc?plain=1#L49

**Comment by LawrenceDLockhart** [comment]
Hi Glenn, it appears [this commit ](https://github.com/spring-cloud/spring-cloud-task/commit/a2145b258adb91e7fd8653176394b285e52298e1) resolves the issue. Do you know if there is more to be done here?

**Comment by cppwfs** [comment]
Good catch!   Sorry about not closing this issue .   Thank you!
