### ISSUE TITLE
Task observability interferes with task execution listener implementations that also implement the ApplicationRunner interface

### ISSUE THREAD

**Issue by ferdinandhuebner** [spring-cloud/spring-cloud-task#936]
### What happened?

Some of our projects implemented a task execution listener by annotating methods with `@BeforeTask` and `@AfterTask`. That task execution listener also implemented the `ApplicationRunner` interface to run the actual task.

Task observability was turned on with the `spring.cloud.task.observation.enabled=true` configuration property. 

`ObservationApplicationRunnerBeanPostProcessor` discovers our `ApplicationRunner` implementation and wraps it into an `ObservationApplicationRunner`. As a result, the task execution listener plumbing in `TaskLifecycleConfiguration` and/or `TaskLifecycleListener` no longer detects the class as a task execution listener and the methods annotated with `@BeforeTask` and `@AfterTask` are no longer executed. 

### What did you expect to happen?

A class that implements `ApplicationRunner` should also be able to implement the `TaskExecutionListener` interface or annotate methods with the `@BeforeTask`, `@AfterTask` or `@FailedTask` without change in behaviour if task observability is turned on.

### How can we reproduce it?

Please find a reproducer here: [ferdinandhuebner/spring-cloud-task-listener-executor-bug](https://github.com/ferdinandhuebner/spring-cloud-task-listener-executor-bug):

- This unit test demonstrates the current and expected behaviour: [TaskListenerExecutorBugTests.java](https://github.com/ferdinandhuebner/spring-cloud-task-listener-executor-bug/blob/main/src/test/java/com/example/tasklistenerexecutorbug/TaskListenerExecutorBugTests.java)
- This is the `ApplicationRunner` implementation that has methods annotated with `@BeforeTask` and `@AfterTask`: [TaskListenerExecutorBugTest](https://github.com/ferdinandhuebner/spring-cloud-task-listener-executor-bug/blob/main/src/main/java/com/example/tasklistenerexecutorbug/FooTaskRunner.java)

### Anything else we need to know?

- Spring Cloud version: `2022.0.4`
- Spring Cloud Task version: `3.0.3`
- Spring Boot version: `3.1.5`

**Comment by cppwfs** [comment]
I'm so sorry for the delayed response.
To resolve your issue you need to update the signature of your @Before task method from 
```
  @BeforeTask
  public void beforeTask(TaskExecution taskExecution) {
    LOG.info("beforeTask was called");
    beforeTaskWasExecuted.set(true);
    executionId = taskExecution.getExecutionId();
  }
  ```
  to
  ```
  @BeforeTask
  public TaskExecution beforeTask(TaskExecution taskExecution) {
    LOG.info("beforeTask was called");
    beforeTaskWasExecuted.set(true);
    executionId = taskExecution.getExecutionId();
    return taskExecution;
  }
  ```

**Comment by cppwfs** [comment]
I'm closing this issue as resolved.   If you think this was closed in error, please add a comment.   Thanks
