### ISSUE TITLE
DefaultTaskConfigurer constructors should use TaskProperties.getTablePrefix() instead of constant TaskProperties.DEFAULT_TABLE_PREFIX

### ISSUE THREAD

**Issue by nightswimmings** [spring-cloud/spring-cloud-task#939]
Right now if one uses DefaultTaskConfigurer without specifying a prefix, it looses the ability to use the one from properties.
I think when not passed as a param, it should use TaskProperties.getTablePrefix() and instead set the default at the TaskProperties  level

Besides, shouldn't "Class.forName("javax.persistence.EntityManager");" be now "Class.forName("jakarta.persistence.EntityManager");" considering this corresponds to the release train for Boot 3.2?

**Comment by cppwfs** [comment]
Thank you for the comment and good catch on the `javax`.   
But, I'm a little confused, as to why we'd want to pass in the TaskProperties to obtain the prefix when other constructors allow for the setting of the prefix?

**Comment by nightswimmings** [comment]
Because if we want to customize only one argument then we don't have to deal with and research internal mechanisms for table prefix
I mean I think it makes sense to assume that as long as you don't pass the tablePrefix as argument, you want to benefit from the default properties mechanism

Think somebody that just wants to pass a custom datasource, then he performs 
 
```
public CustomTaskConfigurer(@BatchDataSource DataSource dataSource) {
        super(dataSource); 
}
```

But then he realises that the tables are being created in another place, he or she needs to research the implementation and understand that you need to reproduce the previous default

```
public CustomTaskConfigurer(@BatchDataSource DataSource dataSource, TaskProperties taskProperties) {
        super(dataSource, taskProperties.getTablePrefix(), null); 
    }
```

**Comment by cppwfs** [comment]
Let's see If we can squeeze this into 3.1.2

**Comment by cppwfs** [comment]
Since this is a change in behavior this will be in the 3.2 release of Task.

**Comment by favna** [comment]
Can you provide any rough estimation whatsoever for when that may be released so I can update our Jira with more information? For now, the story is flagged in the current sprint but if 3.2 won't be coming for some time I'd rather push it back to the backlog.

**Comment by cppwfs** [comment]
This has been pushed to 3.2, based on discussions that a change like this can't be put into a patch release.

**Comment by favna** [comment]
Thanks for the update. I'll wait patiently, no problem. Plenty of other things on our backlog that need doing.

**Comment by cppwfs** [comment]
Rebased Merged

**Comment by favna** [comment]
@cppwfs Might I ask what the release planning is for this package? It's been a few months since the merge but there has been no new release, so we still suffer from this issue.

**Comment by cppwfs** [comment]
@favna Thanks for the question.   It is scheduled for December 5.  https://spring.io/projects#release-calendar
