### ISSUE TITLE
The documentation references old initializr and needs to be updated to avoid confusion.

### ISSUE THREAD

**Issue by dashaun** [spring-cloud/spring-cloud-task#940]
https://docs.spring.io/spring-cloud-task/docs/current/reference/html/#getting-started

1. `In the Dependencies text box, type jdbc and then select the JDBC dependency.`

JDBC?  JDBC API or Spring Data JDBC? Multiple things show up when you type JDBC.

2. `When our sample application runs, Spring Boot launches our HelloWorldCommandLineRunner and outputs our “Hello, World!” message to standard out. The TaskLifecycleListener records the start of the task and the end of the task in the repository.`

3. The example is not using CommandLineRunner, its using ApplicationRunner.

4. The package name in the example doesn't match what we get from Initializr.

5. You don't need to have Maven installed because you get the Maven Wrapper with Initializr.

**Comment by cppwfs** [comment]
Resolved via PR https://github.com/spring-cloud/spring-cloud-task/pull/941.   Thank you for your contribution!
