### ISSUE TITLE
Using MariaDB，TASK_LOCK is not cleared when using single-instance-enabled option. 

### ISSUE THREAD

**Issue by chenmaolin928** [spring-cloud/spring-cloud-task#947]
I have followed the steps in the documentation to implement the single-instance-enabled option for my Spring Cloud Task Application.

I added the following to my application.yml
single-instance-enabled: true

Behavior:
The first task execution will run, record an entry in the task_lock table, task will complete normally. The record is not removed from task_lock even when the task has completed.

The second task execution will fail, because task_lock record still exists from the first run.
MariaDB version 3.1.4
spring-cloud-task-core 3.0.3.RELEASE

I even modified the LOCK_KEY and CLIENT_ID columns in the task_lock table from char(36) to varchar(36), but the situation did not improve.

I have noticed that if I debug and set breakpoints, executing each step of the org.springframework.cloud.task.listener.TaskLifecycleListener#doTaskEnd method, the records in the task_lock table are correctly cleared. However, if I directly run the task, it seems that the task executes too quickly, and the lock is not deleted in time before the program completes. Please consider my observation.

**Comment by cppwfs** [comment]
Can you verify that you added `spring-integration-core` and `spring-integration-jdbc` dependencies as well?  More can be read here:  https://docs.spring.io/spring-cloud-task/docs/current/reference/html/#:~:text=8.9.%20Restricting%20Spring%20Cloud%20Task%20Instances

**Comment by chenmaolin928** [comment]
These two dependencies are already present in my project.
spring-integration-jdbc  6.1.0
spring-integration-core  6.1.0

**Comment by chenmaolin928** [comment]
Thank you very much for your help, but I am unable to provide the business code. In the end, our team has only implemented a solution by manually deleting the records of task_lock. Thank you.

**Comment by chenmaolin928** [comment]
> I was unable to reproduce the scenario. Can you provide a sample application that exhibits the behavior? Thank you!

Thank you very much for your help, but I am unable to provide the business code. In the end, our team has only implemented a solution by manually deleting the records of task_lock. Thank you.

**Comment by cppwfs** [comment]
I'll close this issue.  If you can provide a generic example that exhibits the behavior please reopen the issue.

Thanks for reaching out.
