### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by breun** [spring-cloud/spring-cloud-task#951]
On https://spring.io/projects/spring-cloud-task#learn there are some broken links:

* 3.1.2 links to https://docs.spring.io/spring-cloud-task/docs/current/reference/html/, which shows the documentation for version 3.0.4.
* 3.1.3-SNAPSHOT links to https://docs.spring.io/spring-cloud-task/docs/3.1.3-SNAPSHOT/reference/html/, which returns 404 Not Found.

For 3.1.x the correct URL format seems to be https://docs.spring.io/spring-cloud-task/reference/${version},. because these work:

* 3.1.2: https://docs.spring.io/spring-cloud-task/reference/3.1.2
* 3.1.3-SNAPSHOT: https://docs.spring.io/spring-cloud-task/reference/3.1.3-SNAPSHOT

**Comment by cppwfs** [comment]
Thank you for reporting!

**Comment by breun** [comment]
The link for 3.1.2 still points to https://docs.spring.io/spring-cloud-task/docs/current/reference/html/, which shows the documentation for version 3.0.4. I think this link should point to https://docs.spring.io/spring-cloud-task/reference/

There is also an entry for 3.1-SNAPSHOT, which seems unnecessary, because that version doesn't actually exist, and the link is the same as for 3.1.3-SNAPSHOT, which is a version that does exist.

**Comment by cppwfs** [comment]
@breun Thank you for heads up!    These are now resolved.
